package domain.model.enums;

public enum OperationType {
    ACCOUNT_OPENED,
    ACCOUNT_BLOCKED,
    ACCOUNT_CANCELLED,
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER_CREATED,
    TRANSFER_PENDING_APPROVAL,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    TRANSFER_EXECUTED,
    TRANSFER_EXPIRED,
    LOAN_REQUESTED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_DISBURSED,
    USER_CREATED,
    USER_BLOCKED,
    USER_ACTIVATED,
    CLIENT_REGISTERED,
    CLIENT_UPDATED
}
