package application.model.enums;

public enum SystemRole {
    NATURAL_PERSON_CLIENT,
    COMPANY_CLIENT,
    TELLER_EMPLOYEE,
    COMMERCIAL_EMPLOYEE,
    COMPANY_EMPLOYEE,
    COMPANY_SUPERVISOR,
    INTERNAL_ANALYST
}